# Generated by Django 5.2.5 on 2025-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(default='/shop', help_text='/clothes', max_length=255),
        ),
    ]
