# Generated by Django 5.2.5 on 2025-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL path for the button (e.g., /men).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text="Text for the button (e.g., 'Shop Now').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='The wide, landscape image for desktop screens.', null=True, upload_to='banners/wide/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this box to make the banner visible on the site.'),
        ),
    ]
