# Generated by Django 5.2.5 on 2025-09-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL path for the button (e.g., /men).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text="Text for the call-to-action button (e.g., 'Shop Now').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(default='/shop', help_text='e.g., /women, /shop, /product/12', max_length=255),
        ),
    ]
