# Generated by Django 5.2.5 on 2025-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.CharField(max_length=255)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
