# Generated by Django 5.2.5 on 2025-09-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
